<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
    <?php
        if ($block->isLoggedIn()) {
    ?>
    <ul class="dropdown-link">
        <li><a href="<?php echo $this->getUrl('customer/account')  ?>"><?php echo __('my account'); ?></a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/logout')  ?>"><?php echo __('sign out'); ?></a></li>
    </ul>
    <?php } ?>
</li>
