<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_PDFCustom
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var \Amasty\PDFCustom\Block\Sales\Order\AdditionalButton $block */
?>
<a class="action order"
   href="<?= /* @escapeNotVerified */ $block->getPdfUrl() ?>"
   onclick="this.target='_blank';">
    <span><?= /* @escapeNotVerified */ $block->getLinkLabel() ?></span>
</a>
