<script>
require([
    'jquery',
    'Magento_Ui/js/modal/alert',
    'prototype'
], function(jQuery, alert){
    function customer_sync() {
        params = {
        };

        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            loaderArea:     true,
            asynchronous:   true,
            parameters:     params,
            onSuccess: function(transport) {
                alert({
                    content: 'Customer Sync is completed.'
                })
            }
        });
    }

    jQuery('#custSync').click(function () {
        customer_sync();
    });
});
</script>

<?php echo $block->getButtonHtml() ?>