<?php
/**
 * MageVision Cart Product Comment Extension
 *
 * @category     MageVision
 * @package      MageVision_CartProductComment
 * @author       MageVision Team
 * @copyright    Copyright (c) 2018 MageVision (http://www.magevision.com)
 * @license      LICENSE_MV.txt or http://www.magevision.com/license-agreement/
 */
?>
<?php $_item = $block->getItem(); ?>
<?php $_order = $_item->getOrder(); ?>
<?php $cartProductCommentHelper = $this->helper('MageVision\CartProductComment\Helper\Data'); ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?php echo $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?php /* @escapeNotVerified */ echo __('SKU'); ?>: <?php echo $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?php /* @escapeNotVerified */ echo $option['label'] ?></em></strong></dt>
                <dd>
                    <?php /* @escapeNotVerified */ echo nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
        <?php if ($cartProductCommentHelper->isEnabled() && $_item->getComment()): ?>
            <p class="comment"><?php /* @escapeNotVerified */ echo __('Comment'); ?>: <?php echo $block->escapeHtml($_item->getComment()) ?></p>
        <?php endif; ?>
    </td>
    <td class="item-qty"><?php /* @escapeNotVerified */ echo $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?php /* @escapeNotVerified */ echo $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?php /* @escapeNotVerified */ echo __('Gift Message') ?></h3>
                    <strong><?php /* @escapeNotVerified */ echo __('From:'); ?></strong> <?php echo $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?php /* @escapeNotVerified */ echo __('To:'); ?></strong> <?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?php /* @escapeNotVerified */ echo __('Message:'); ?></strong>
                    <br /><?php echo $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
